/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'product' : Product }
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'user' : Principal,
  'timestamp' : bigint,
  'items' : Array<CartItem>,
  'shippingDetails' : ShippingDetails,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'whatsappNumber' : string,
  'stock' : bigint,
  'category' : ProductCategory,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ProductCategory = { 'clothing' : null } |
  { 'home' : null } |
  { 'books' : null } |
  { 'sports' : null } |
  { 'electronics' : null };
export interface ShippingDetails {
  'city' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface UserProfile {
  'city' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[ShippingDetails], string>,
  'clearCart' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<
    [string, string, bigint, ExternalBlob, string, ProductCategory, bigint],
    string
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getLowStockCount' : ActorMethod<[bigint], bigint>,
  'getLowStockProducts' : ActorMethod<[bigint], Array<Product>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getPendingOrdersCount' : ActorMethod<[], bigint>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductStock' : ActorMethod<[string], bigint>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getTotalOrders' : ActorMethod<[], bigint>,
  'getTotalProducts' : ActorMethod<[], bigint>,
  'getTotalRevenue' : ActorMethod<[], bigint>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartQuantity' : ActorMethod<[string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      ExternalBlob,
      string,
      ProductCategory,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];